apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx 
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'nginx-role'
        vault.hashicorp.com/agent-inject-file-htpasswd: '.htpasswd'
        vault.hashicorp.com/secret-volume-path: '/etc/apache2/'
        vault.hashicorp.com/agent-inject-template-htpasswd: |
          {{- with secret "kv/nginx/basic-auth" -}}
          {{ .Data.data.htpasswd }}
          {{- end -}}
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
          - name: vo-conf
            mountPath: "/etc/nginx/conf.d"
            readOnly: true
      volumes:
        - name: vo-conf
          configMap:
            name: nginx-conf
            items:
              - key: "default.conf"
                path: "default.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
